Block selection changes
trosh/1010 pull request #2
Opened 2017-05-10 02:34 UTC by pickedusername11

No block is selected by default.
Added keys to select previous/next block - this makes it easier to play with one hand.

2017-05-10 06:29 UTC, trosh requested changes
Please change the `<` / `>` stuff however you like, and the rest if you feel like it.

2017-05-10 06:29 UTC, trosh commented on README.md
> -- **ESCAPE/Q** TO QUIT
why git thinks this was modified still baffles me

2017-05-10 06:29 UTC, trosh commented on main.c
> +    char oldb;   /* PREVIOUSY SELECTED BLOCK, REQUIRED FOR NEXT/PREV BLOCK */
well, only required if you don't want the position to reset when switching blocks with no other block available

2017-05-10 06:29 UTC, trosh commented on main.c
> +            if (b <3)   printbk(bks[b], x, y, b+3);
heh, `<3` is cute, but maybe use `-1` for no selection, and `b >= 0` for the test (I think `3` seems to much of a legal value)

2017-05-10 06:29 UTC, trosh commented on main.c
> +                }
```c
else b = 0;
```
?

2017-05-10 06:29 UTC, trosh commented on main.c
> +                    while (!bka[++b%3]) {}
```c
b += 3;
do b--; while (!bka[b%3]);
```
or
```c
b += 2;
while (!bka[b%3]) b--;
```

2017-05-10 06:29 UTC, trosh commented on main.c
> +                    while (!bka[++b%3]) {}
```c
do ++b; while (!bka[b%3]);
```

2017-05-10 06:29 UTC, trosh commented on main.c
> +                if (b < 3 && x > 0
If this got too repetitive, you could maybe leave these cases in another `switch` executed only if a block is selected.

2017-05-10 06:29 UTC, trosh commented on main.c
> +        }
ooookay i just understood why you're doing this (selecting directly when there's only one left).
I feel like it makes sense but at the same time it slightly breaks the flow of choosing your block.

Testing if any block is left could be reduced to `if (bka[0] || bka[1] || bka[2])`
if you wanted the code to look homogeneously obfuscated lol (actually that feels more readable than temporarily using `b` to count available blocks).

2017-05-10 06:38 UTC, trosh commented
This is the first time someone contributed to a project by me so it's great,
thanks for doing this, and I still have no idea how you found this.

You didn't need to re-fork your repo just because our histories diverged.
If you accepted to discard your side of history you could have done something like
```sh
$ git remote add trosh https://github.com/trosh/1010
$ git fetch trosh master
$ git reset --hard trosh/master
```

The grid is quite nice, I'll look into coloring the borders between colored tiles.

2017-05-10 06:42 UTC, pickedusername11 commented
Your notes look reasonable, apart from the bit about the </> comment - didn't get what's wrong there.
But, this is where my knowledge of github ends. I have no idea how to make/accept changes.
Feel free to incorporate my changes any way you like.

I found you by searching for a console version of 1010 ;o)
I only use the web interface, not the command-line git, this is why I did the most obvious thing to catch up with your changes.

2017-05-10 06:48 UTC, trosh commented
`<`/`>` should select blocks when `b == 3` (`<` should set `b = 2` and `>` should set `b = 0`)

Also currently `<` acts like `>` (you increment b in both cases).
I was suggesting two ways of decrementing (while avoiding going below zero which breaks the modulo).

Great to know that you had the same idea for the game :smiley:

I can only suggest using Git, because while Github is nice for communicating,
real magic is always in Git which will always always work.

2017-05-10 07:00 UTC, trosh commented on main.c
> +        }
oops that should be `if (bka[0] + bka[1] + bka[2] == 1)`

2017-05-10 07:07 UTC, pickedusername11 commented
Ah, I see where the confusion comes from.
It was not meant to be three keys '<', '/' and '>', that meant either < or >.
More like scrolling left and right. The slash on it's own does nothing.
Similarly, ',' and '.' were supposed to work the same way as '<' and '>", just without the shift key.
One day I may indeed learn a bit of git. Right now I hate it with passion.

2017-05-10 07:24 UTC, trosh commented
You're not getting me &mdash; I'm aware of what you're trying to do, I'm just saying right now it's not doing that. `<` and `,` both do like `>` and `.`; they don't select leftwards but righwards.
```c
case 60 : /* < */
    if (b < 3) { /* IF SOME BLOCK IS SELECTED */
        oldb = b;
        while (!bka[++b%3]) {}
```
This increments `b`, just like the following case does. I'm telling you to decrement instead, but warn you to beware of negative modulo (-1 mod 3 is -1, not 2 as one might expect), and I commented two ways to do that.

Also I think that when nothing is selected, it's annoying to press one of these "scroll" keys with nothing happening, so I suggest allowing `b` to go from 3 to 0 or 2 depending on the direction.

Furthermore I'm personally not fond of using these keys instead of 1/2/3, and I don't even know how it's practical to you to use only one hand &mdash; but since you added it it's fine by me.

Git is love, Git is life

2017-05-12 00:17 UTC, pickedusername11 commented
Ah, OK. Now I get it.
These were not supposed to be used instead of 1,2,3. Just in addition to.
To have both absolute and relative block changing.

2017-05-12 03:06 UTC, pickedusername11 commented
I just thought a bit, and think you are right. To select an initial block you have to use 1,2,3 anyway. So no easy one-handed playing. Just throw away that < / > bits then.

Regarding the grid - do you think it may make sense to use the underline attribute for horizontal grid lines? That would probably save some vertical space.

2017-05-12 08:31 UTC, trosh commented
OK I integrated your changes, and I kept the `<`/`>` stuff, see if you like how it acts now. Otherwise you can remove that bit of code.

I also improved the display of blocks (connected the tiles together).

I'm thinking that using Unicode upper and left half blocks and corner blocks (or a curses equivalent if there's such a thing) alongside ACS lines could allow filling the grid tiles when coloring. See what I mean ? the grid wouldn't be visible inside blocks (or filled areas) though, so it might be better to use the existing display in the hint board and a filled display in the game board (you can visualize the grid with the surrounding area).

2017-05-12 08:32 UTC, closed without merging

2017-05-12 10:42 UTC, pickedusername11 commented
Looks great. Thank you.
One minor suggestion - change the clean target in the Makefile to:

clean:
        rm -f ./1010

I think this is a better way to avoid the error message if ./1010 does not exist.
Regarding the upper/lower half blocks - check this link:
http://owlwd.tk/2014/01/30/displaying-conway-s-game-of-life-using-ncurses
Do you like any of the approaches tried there?

2017-05-12 10:57 UTC, trosh commented
The article is a good example of using the block characters (in a possibly portable way, not sure), but it doesn't give any more answer for getting a visual grid to look good.

2017-05-12 13:26 UTC, trosh commented
hmm my idea of using unicode corner blocks is doomed to fail because some situations would require three colors in a cell